name: flutter_bcrypt
description: A flutter bcrypt hashing plugin delegating to android &#x2F; ios native implementations.
version: 1.0.7
homepage: https://github.com/jeroentrappers/flutter_bcrypt

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: be.appmire.flutter_bcrypt
        pluginClass: FlutterBcryptPlugin
      ios:
        pluginClass: FlutterBcryptPlugin

